// ===== KREATIVA NETWORK — i18n (id / en / ar / ru) =====
// Bahasa Indonesia diambil otomatis dari isi HTML (snapshot).
// EN / AR / RU didefinisikan di bawah. Arab otomatis RTL.
var KN_LANGS = ["id", "en", "ar", "ru"];
var KN_WA_NUM = "62895637319465";

var I18N = {
id: {
  docTitle: "Kreativa Network — Jasa Kreatif & Digital (IT, Software, Advertising, Design)",
  metaDesc: "Kreativa Network — partner jasa kreatif & digital: IT solution, software development, advertising, dan design. Konsultasi gratis via WhatsApp.",
  waFormTpl: "Halo Kreativa Network! Saya {nama}. Saya butuh: {butuh}. Mohon info & penawarannya, terima kasih.",
  toastThanks: "Terima kasih {nama}! Membuka WhatsApp…",
  rotWords: ["Mesin Penjualan", "Brand Premium", "Omzet Berlipat", "Bisnis Naik Kelas"]
},
en: {
  docTitle: "Kreativa Network — Creative & Digital Services (IT, Software, Advertising, Design)",
  metaDesc: "Kreativa Network — your creative & digital partner: IT solutions, software development, advertising, and design. Free consultation via WhatsApp.",
  waFormTpl: "Hello Kreativa Network! I'm {nama}. I need: {butuh}. Please send info & a quote, thanks.",
  toastThanks: "Thanks {nama}! Opening WhatsApp…",
  rotWords: ["Sales Machine", "Premium Brand", "Soaring Revenue", "Growing Business"],
  preText: "Preparing your digital experience…",
  topText: "This month's promo: <strong>20% off</strong> company profile + logo branding",
  topClaim: "Claim Promo →",
  nHome: "Home", nSvc: "Services", nWhy: "Why Us", nPorto: "Portfolio", nHarga: "Pricing", nFaq: "FAQ", nKontak: "Contact",
  navCta: "Free Consultation", hamAria: "Open menu",
  badge: "#1 Creative & Digital Partner for SMEs – Corporates",
  h1a: "Build Your", h1dream: "Dream Brand", h1b: "Into a",
  lead: "Kreativa Network helps businesses <span class=\"hl\" style=\"--d:1s\'>level up</span> through <strong>IT solutions, software, advertising, & design</strong> — <span class=\"hl\" style=\"--d:1.15s\'>one door</span>, <span class=\"hl\" style=\"--d:1.3s\'>measurable results</span>, <span class=\"hl\" style=\"--d:1.45s\'>revision guarantee</span>.",
  heroWa: "Chat on WhatsApp Now", heroSvc: "View Services ↓",
  trust: "<strong>120+ happy clients</strong> · 4.9/5 rating from verified reviews",
  mockStatL: "Client Revenue", mockStatT: "▲ 6 months",
  mWeb: "Company Profile Website", mAds: "Meta Ads Campaign", mLogo: "Logo Rebranding", mDone: "Done",
  f1: "Unlimited Revisions*", f2: "Launch &lt; 14 Days",
  lblProj: "Projects Completed", lblCli: "Active Clients", lblExp: "Experience", lblHappy: "Happy Clients", sfxYr: "yrs",
  svcKick: "FEATURED SERVICES",
  svcH2: "One Partner for All Your <span class=\"grad\'>Digital Needs</span>",
  svcSub: "Click each service for details, then consult directly via WhatsApp.",
  tabIt: "IT Solution", tabSw: "Software", tabAds: "Advertising", tabDes: "Design",
  itH: "IT Solutions & Infrastructure",
  itP: "Secure, fast, scale-ready technology foundations for your business operations.",
  itLi1: "Company profile websites, e-commerce & landing pages",
  itLi2: "Maintenance, security & regular server backups",
  itLi3: "System integrations: payment gateways, CRM, ERP, APIs",
  itLi4: "IT consulting & audits to cut costs",
  itPrice: "From <strong>Rp 1,5 jt</strong>", itBtn: "Choose This Service →",
  itArt: "Fast, secure & SEO-friendly websites",
  swH: "Software Development",
  swP: "Custom apps that cut manual work and accelerate growth.",
  swLi1: "Android & iOS mobile apps (Flutter / React Native)",
  swLi2: "Information systems: POS, inventory, HRIS, academic, clinic",
  swLi3: "Dashboards & real-time report automation",
  swLi4: "You own the source code + full documentation",
  swPrice: "From <strong>Rp 8 jt</strong>", swBtn: "Choose This Service →",
  swArt: "Custom apps matching your business flow",
  adH: "Advertising & Digital Marketing",
  adP: "Ads with transparent data — every rupiah tracked.",
  adLi1: "Meta Ads, Google Ads, TikTok Ads — setup + optimization",
  adLi2: "SEO & content marketing for organic traffic",
  adLi3: "Social media management + persuasive copywriting",
  adLi4: "Easy-to-read weekly performance reports",
  adPrice: "From <strong>Rp 2,5 jt/mo</strong>", adBtn: "Choose This Service →",
  adArt: "Average client ROAS 4–6x",
  deH: "Design & Branding",
  deP: "Premium visuals that make your brand look expensive and trusted.",
  deLi1: "Logo & brand identity (complete guideline)",
  deLi2: "UI/UX design for web & apps",
  deLi3: "Feed, banner, packaging & company profile design",
  deLi4: "Revision guarantee until you're satisfied*",
  dePrice: "From <strong>Rp 750 rb</strong>", deBtn: "Choose This Service →",
  deArt: "Print & digital-ready brand guidelines",
  advKick: "WHY US",
  advH2: "Why 120+ Businesses Trust <span class=\"grad\'>Kreativa Network</span>",
  c1h: "30+ Years of Combined Experience",
  c1p: "Senior cross-disciplinary team — proven marketing strategies, no guesswork.",
  c2h: "Fast & On Time",
  c2p: "Clear timelines in the contract. Websites launch in &lt; 14 days, revisions answered in &lt; 24 hours.",
  c3h: "Transparent Pricing",
  c3p: "Upfront cost breakdown, no hidden fees. Flexible for SME budgets.",
  c4h: "Guarantee & After-Sales",
  c4p: "Revision guarantee, 30-day bug warranty, and post-launch assistance.",
  c5h: "Data-Driven",
  c5p: "Every decision backed by research & analytics — measurable results, not just good looks.",
  c6h: "One Door, All Done",
  c6p: "IT, software, ads, and design in one team — save coordination & cost.",
  poKick: "PORTFOLIO",
  poH2: "Work That Speaks <span class=\"grad\'>Through Numbers</span>",
  chipAll: "All", chipWeb: "Website & App", chipBrand: "Branding", chipAds: "Ads",
  w1h: "Fashion Online Store", w1p: "E-commerce + payment gateway · <strong>+187% revenue</strong>",
  w2h: "Nusantara Coffee Rebranding", w2p: "Logo + packaging · <strong>+64% repeat orders</strong>",
  w3h: "Beauty Clinic Meta Ads", w3p: "Lead generation · <strong>5.2x ROAS</strong>",
  w4h: "School Academic System", w4p: "Web app + online admission · <strong>saves 20 hrs/week</strong>",
  w5h: "Property Company Profile", w5p: "Premium profile + brochure · <strong>+41% closings</strong>",
  w6h: "Culinary TikTok Ads", w6p: "Content + ads · <strong>3.2M views / 30 days</strong>",
  poMore: "Request Full Portfolio →",
  stKick: "HOW IT WORKS",
  stH2: "From First Chat to <span class=\"grad\'>Launch</span> — This Easy",
  s1h: "Free Consultation", s1p: "Chat on WhatsApp, tell us your business needs & goals.",
  s2h: "Proposal & Design", s2p: "Receive a transparent quote + initial concept in 2–3 days.",
  s3h: "Execution & Revisions", s3p: "Track real-time progress, revise until you're satisfied.",
  s4h: "Launch & Assistance", s4p: "Official release + training + 30-day assistance warranty.",
  teKick: "TESTIMONIALS",
  teH2: "What Those Who <span class=\"grad\'>Leveled Up</span> Say",
  q1: "“Kreativa's website made my business look professional. Online orders doubled in 3 months!”<footer>— <strong>Andi R.</strong>, Fashion Store Owner</footer>",
  q2: "“Neat ads, clear reports. Our ROAS stays above 4x. Highly recommended.”<footer>— <strong>Bella T.</strong>, Clinic Marketing Manager</footer>",
  q3: "“Their academic system drastically cut our admin work. Support is fast too.”<footer>— <strong>H. Mahmud</strong>, School Principal</footer>",
  prKick: "INVESTMENT",
  prH2: "Honest Prices, <span class=\"grad\'>Maximum Results</span>",
  prSub: "All packages are customizable. Click to discuss your needs.",
  p1n: "Starter", p1s: "For SMEs just starting out", uJt: " jt",
  p1li1: "1-page landing page", p1li2: "Basic copywriting", p1li3: "WhatsApp integration", p1li4: "2 revisions · 7-day release",
  p1b: "Choose Starter",
  hot: "BEST SELLER", p2n: "Business", p2s: "For growing businesses", uJt2: " jt",
  p2li1: "5–8 page company profile", p2li2: "Logo + brand mini-kit", p2li3: "Basic SEO + analytics", p2li4: "5 revisions · 14-day release",
  p2b: "Choose Business",
  p3n: "Enterprise", p3s: "Large-scale software & campaigns", p3c: "Custom",
  p3li1: "Apps / information systems", p3li2: "Ads management + creatives", p3li3: "Dedicated project manager", p3li4: "SLA & priority warranty",
  p3b: "Request a Quote",
  fqKick: "FAQ",
  fqH2: "Frequently <span class=\"grad\'>Asked Questions</span>",
  f1q: "How long does a website take?",
  f1a: "Landing pages ±7 days, company profiles ±14 days, custom apps 1–3 months depending on complexity. Timelines are clearly stated in the contract.",
  f2q: "Is there a revision guarantee?",
  f2a: "Yes. Every package includes revision quotas, and for design the guarantee applies until you're satisfied within agreed fair limits.",
  f3q: "How does payment work?",
  f3a: "50% deposit to start, balance after handover. Installments available for large projects. Everything recorded in official invoices & contracts.",
  f4q: "Will I own the source code?",
  f4a: "Yes, for custom website/software projects the full source code + documentation is handed over after final payment.",
  f5q: "Do you serve clients outside the city?",
  f5a: "Of course. 70% of our clients are out of town — the whole process runs online (WhatsApp, Zoom, progress dashboard) with the same neat results.",
  ctaH2: "Ready to Make Your Business Look <span class=\"grad'>Premium & Trusted?</span>",
  ctaP: "<strong>100% free consultation, no commitment</strong>. Tell us your needs — we'll reply with solutions & cost estimates within 24 hours.",
  fNamaPh: "Your name", fButuhPh: "— I need… —",
  opt1: "Website / IT Solution", opt2: "Software / App", opt3: "Advertising / Digital Marketing", opt4: "Design / Branding", opt5: "Other / Just consulting",
  submit: "Send via WhatsApp",
  ctaAlt: "Or chat directly: <a href=\"https://wa.me/62895637319465\" target=\"_blank\" rel=\"noopener\'><strong>+62 895-6373-19465</strong></a>",
  ftDesc: "Creative & digital services: IT solutions, software development, advertising, and design. One partner for brands ready to level up.",
  ftSvc: "Services", ftNav: "Navigation", ftHub: "Contact Us",
  ftHours: "Monday–Saturday · 09.00–18.00 WIB",
  ftBase: "© <span id=\"year\'></span> Kreativa Network. All rights reserved. <span class=\"syarat\'>*Warranty terms & conditions apply.</span>",
  waAria: "Chat on WhatsApp", topAria: "Back to top", toastInit: "Opening WhatsApp…",
  promo: "Hello Kreativa Network! I'm interested in the 20% discount promo.",
  nav: "Hello Kreativa Network! I'd like a free consultation.",
  hero: "Hello Kreativa Network! I'd like a free consultation about my business's digital needs.",
  it: "Hello Kreativa Network! I need IT Solution services.",
  sw: "Hello Kreativa Network! I need software/app development.",
  ads: "Hello Kreativa Network! I need advertising/digital marketing services.",
  des: "Hello Kreativa Network! I need design/branding services.",
  porto: "Hello Kreativa Network! I'd like to see the full portfolio.",
  starter: "Hello Kreativa Network! I'm interested in the Starter package.",
  bisnis: "Hello Kreativa Network! I'm interested in the Business package.",
  enter: "Hello Kreativa Network! I'd like a quote for the Enterprise package.",
  float: "Hello Kreativa Network! I'd like a consultation."
},
ar: {
  docTitle: "كرياتيفا نتورك — خدمات إبداعية ورقمية (تقنية وبرمجيات وإعلان وتصميم)",
  metaDesc: "كرياتيفا نتورك — شريكك الإبداعي والرقمي: حلول تقنية وتطوير برمجيات وإعلان وتصميم. استشارة مجانية عبر واتساب.",
  waFormTpl: "مرحباً كرياتيفا نتورك! أنا {nama}. أحتاج: {butuh}. أرجو إرسال المعلومات والعرض، شكراً.",
  toastThanks: "شكراً {nama}! جارٍ فتح واتساب…",
  rotWords: ["ماكينة مبيعات", "براند فاخر", "أرباح مضاعفة", "نمو الأعمال"],
  preText: "جارٍ تجهيز تجربتك الرقمية…",
  topText: "عرض هذا الشهر: <strong>خصم 20%</strong> على الملف التعريفي للشركة + تصميم الشعار",
  topClaim: "← احصل على العرض",
  nHome: "الرئيسية", nSvc: "الخدمات", nWhy: "لماذا نحن", nPorto: "الأعمال", nHarga: "الأسعار", nFaq: "الأسئلة الشائعة", nKontak: "اتصل بنا",
  navCta: "استشارة مجانية", hamAria: "افتح القائمة",
  badge: "الشريك الإبداعي والرقمي الأول للشركات الصغيرة والكبيرة",
  h1a: "اصنع علامتك", h1dream: "التجارية التي تحلم بها", h1b: "لتصبح",
  lead: "تساعد كرياتيفا نتورك عملك على <span class=\"hl\" style=\"--d:1s\'>الارتقاء</span> عبر <strong>حلول تقنية وبرمجيات وإعلان وتصميم</strong> — <span class=\"hl\" style=\"--d:1.15s\'>باب واحد</span>، <span class=\"hl\" style=\"--d:1.3s\'>نتائج قابلة للقياس</span>، <span class=\"hl\" style=\"--d:1.45s\'>ضمان التعديلات</span>.",
  heroWa: "تحدث واتساب الآن", heroSvc: "↓ عرض الخدمات",
  trust: "<strong>+120 عميل سعيد</strong> · تقييم 4.9/5 من مراجعات موثقة",
  mockStatL: "إيرادات العملاء", mockStatT: "▲ 6 أشهر",
  mWeb: "موقع تعريفي للشركة", mAds: "إعلانات ميتا", mLogo: "إعادة تصميم الشعار", mDone: "تم",
  f1: "تعديلات بلا حدود*", f2: "الإطلاق &lt; 14 يوم",
  lblProj: "مشاريع منجزة", lblCli: "عملاء نشطون", lblExp: "خبرة", lblHappy: "عملاء سعداء", sfxYr: "سنوات",
  svcKick: "خدمات مميزة",
  svcH2: "شريك واحد لكل احتياجاتك <span class=\"grad\'>الرقمية</span>",
  svcSub: "انقر على كل خدمة للتفاصيل، ثم استشرنا مباشرة عبر واتساب.",
  tabIt: "حلول تقنية", tabSw: "برمجيات", tabAds: "إعلان", tabDes: "تصميم",
  itH: "حلول تقنية وبنية تحتية",
  itP: "أساس تقني آمن وسريع وقابل للتوسع لعمليات عملك.",
  itLi1: "مواقع تعريفية ومتاجر إلكترونية وصفحات هبوط",
  itLi2: "صيانة وأمان ونسخ احتياطي دوري للخوادم",
  itLi3: "تكامل الأنظمة: بوابات الدفع وCRM وERP وAPI",
  itLi4: "استشارات وتدقيق تقني لخفض التكاليف",
  itPrice: "ابتداءً من <strong>Rp 1,5 jt</strong>", itBtn: "← اختر هذه الخدمة",
  itArt: "مواقع سريعة وآمنة وصديقة لمحركات البحث",
  swH: "تطوير البرمجيات",
  swP: "تطبيقات مخصصة تختصر العمل اليدوي وتسرّع النمو.",
  swLi1: "تطبيقات أندرويد وiOS (Flutter / React Native)",
  swLi2: "أنظمة معلومات: نقاط بيع ومخزون وموارد بشرية وأكاديمية وعيادات",
  swLi3: "لوحات متابعة وأتمتة التقارير لحظياً",
  swLi4: "الكود المصدري ملك لك + توثيق كامل",
  swPrice: "ابتداءً من <strong>Rp 8 jt</strong>", swBtn: "← اختر هذه الخدمة",
  swArt: "تطبيقات مخصصة تناسب سير عملك",
  adH: "الإعلان والتسويق الرقمي",
  adP: "إعلانات بشفافية كاملة — كل روبية محسوبة النتائج.",
  adLi1: "إعلانات ميتا وجوجل وتيك توك — إعداد وتحسين",
  adLi2: "SEO وتسويق المحتوى للزيارات المجانية",
  adLi3: "إدارة السوشيال ميديا + كتابة إعلانية مقنعة",
  adLi4: "تقارير أداء أسبوعية سهلة القراءة",
  adPrice: "ابتداءً من <strong>Rp 2,5 jt شهرياً</strong>", adBtn: "← اختر هذه الخدمة",
  adArt: "متوسط عائد عملائنا 4–6 أضعاف",
  deH: "التصميم والهوية",
  deP: "تصاميم فاخرة تجعل علامتك تبدو راقية وموثوقة.",
  deLi1: "شعارات وهوية بصرية (دليل متكامل)",
  deLi2: "تصميم UI/UX للمواقع والتطبيقات",
  deLi3: "تصميم منشورات وبنرات وتغليف وملفات تعريفية",
  deLi4: "ضمان التعديل حتى الرضا*",
  dePrice: "ابتداءً من <strong>Rp 750 rb</strong>", deBtn: "← اختر هذه الخدمة",
  deArt: "دليل هوية جاهز للطباعة والرقمي",
  advKick: "لماذا نحن",
  advH2: "سبب ثقة أكثر من 120 شركة <span class=\"grad\'>بكرياتيفا نتورك</span>",
  c1h: "خبرة متراكمة +30 عاماً",
  c1p: "فريق senior متعدد التخصصات — استراتيجيات تسويق مجرّبة لا تخمين.",
  c2h: "سرعة والتزام بالمواعيد",
  c2p: "جدول زمني واضح في العقد. إطلاق المواقع في أقل من 14 يوماً، والرد على التعديلات خلال 24 ساعة.",
  c3h: "أسعار شفافة",
  c3p: "تفصيل التكاليف مقدماً وبلا رسوم خفية. مرونة تناسب ميزانيات المشاريع الصغيرة.",
  c4h: "ضمان وخدمة ما بعد البيع",
  c4p: "ضمان التعديلات وضمان الأخطاء 30 يوماً ومرافقة بعد الإطلاق.",
  c5h: "قرارات مبنية على البيانات",
  c5p: "كل قرار مدعوم بالبحث والتحليل — نتائج قابلة للقياس لا مجرد شكل جميل.",
  c6h: "باب واحد لكل شيء",
  c6p: "التقنية والبرمجيات والإعلان والتصميم في فريق واحد — وفّر التنسيق والتكلفة.",
  poKick: "الأعمال",
  poH2: "أعمال تتحدث <span class=\"grad\'>بالأرقام</span>",
  chipAll: "الكل", chipWeb: "مواقع وتطبيقات", chipBrand: "هويات", chipAds: "إعلانات",
  w1h: "متجر أزياء إلكتروني", w1p: "متجر إلكتروني + بوابة دفع · <strong>إيرادات +187%</strong>",
  w2h: "إعادة هوية مقهى نوسانتارا", w2p: "شعار + تغليف · <strong>تكرار الشراء +64%</strong>",
  w3h: "إعلانات ميتا لعيادة تجميل", w3p: "توليد عملاء محتملين · <strong>عائد 5.2x</strong>",
  w4h: "نظام أكاديمي مدرسي", w4p: "تطبيق ويب + قبول أونلاين · <strong>توفير 20 ساعة أسبوعياً</strong>",
  w5h: "ملف تعريفي عقاري", w5p: "ملف + بروشور فاخر · <strong>إغلاق صفقات +41%</strong>",
  w6h: "إعلانات تيك توك لمطعم", w6p: "محتوى + إعلانات · <strong>3.2 مليون مشاهدة / 30 يوم</strong>",
  poMore: "← اطلب ملف الأعمال الكامل",
  stKick: "منهجية العمل",
  stH2: "من أول رسالة حتى <span class=\"grad\'>الإطلاق</span> — بهذه السهولة",
  s1h: "استشارة مجانية", s1p: "راسلنا واتساب واحكِ لنا احتياجات عملك وأهدافه.",
  s2h: "عرض وتصميم", s2p: "استلم عرضاً شفافاً + فكرة أولية خلال 2–3 أيام.",
  s3h: "تنفيذ وتعديلات", s3p: "تابع التقدم لحظياً وعدّل حتى الرضا.",
  s4h: "إطلاق ومرافقة", s4p: "إطلاق رسمي + تدريب + ضمان مرافقة 30 يوماً.",
  teKick: "آراء العملاء",
  teH2: "ماذا قال من <span class=\"grad\'>ارتقوا</span> معنا",
  q1: "“موقع كرياتيفا جعل عملي يبدو احترافياً. تضاعفت طلبات الأونلاين خلال 3 أشهر!”<footer>— <strong>أندي ر.</strong>، صاحب متجر أزياء</footer>",
  q2: "“إعلانات مرتبة وتقارير واضحة. عائدنا ثابت فوق 4 أضعاف. أنصح بهم بشدة.”<footer>— <strong>بيلا ت.</strong>، مديرة تسويق عيادة</footer>",
  q3: "“النظام الأكاديمي خفّض عمل الإدارة جذرياً. والدعم سريع الاستجابة.”<footer>— <strong>الحاج محمود</strong>، مدير مدرسة</footer>",
  prKick: "الاستثمار",
  prH2: "أسعار صادقة <span class=\"grad\'>ونتائج قصوى</span>",
  prSub: "كل الباقات قابلة للتخصيص. انقر لمناقشة احتياجك.",
  p1n: "الانطلاقة", p1s: "للمشاريع الصغيرة الناشئة", uJt: " jt",
  p1li1: "صفحة هبوط واحدة", p1li2: "كتابة إعلانية أساسية", p1li3: "ربط واتساب", p1li4: "تعديلان · إطلاق خلال 7 أيام",
  p1b: "اختر باقة الانطلاقة",
  hot: "الأكثر مبيعاً", p2n: "الأعمال", p2s: "للأعمال المتنامية", uJt2: " jt",
  p2li1: "ملف تعريفي 5–8 صفحات", p2li2: "شعار + هوية مصغرة", p2li3: "SEO أساسي + تحليلات", p2li4: "5 تعديلات · إطلاق 14 يوم",
  p2b: "اختر باقة الأعمال",
  p3n: "المؤسسات", p3s: "برمجيات وحملات واسعة", p3c: "مخصص",
  p3li1: "تطبيقات / أنظمة معلومات", p3li2: "إدارة إعلانات + إبداع", p3li3: "مدير مشروع مخصص", p3li4: "اتفاقية خدمة وضمان أولوية",
  p3b: "اطلب عرض سعر",
  fqKick: "الأسئلة الشائعة",
  fqH2: "أسئلة <span class=\"grad\'>تتكرر كثيراً</span>",
  f1q: "كم تستغرق صناعة الموقع؟",
  f1a: "صفحة الهبوط ±7 أيام، والملف التعريفي ±14 يوماً، والتطبيقات المخصصة 1–3 أشهر حسب التعقيد. الجدول الزمني موثق بوضوح في العقد.",
  f2q: "هل يوجد ضمان للتعديلات؟",
  f2a: "نعم. كل باقة تشمل حصة تعديلات، وفي التصميم يسري ضمان التعديل حتى الرضا ضمن المتفق عليه.",
  f3q: "كيف نظام الدفع؟",
  f3a: "عربون 50% للبدء والباقي عند التسليم. وتتوفر دفعات مرحلية للمشاريع الكبيرة. كل شيء موثق بفواتير وعقود رسمية.",
  f4q: "هل الكود المصدري ملك لي؟",
  f4a: "نعم، في مشاريع المواقع والبرمجيات المخصصة يُسلَّم الكود الكامل + التوثيق بعد سداد المستحقات.",
  f5q: "هل تخدمون عملاء خارج المدينة؟",
  f5a: "بالتأكيد. 70% من عملائنا خارج المدينة — تتم العملية أونلاين (واتساب وزوم ولوحة متابعة) بالجودة نفسها.",
  ctaH2: "جاهز لتجعل عملك يبدو <span class=\"grad\'>فاخراً وموثوقاً؟</span>",
  ctaP: "<strong>استشارة مجانية 100% وبلا التزام</strong>. احكِ لنا احتياجك — نرد عليك بالحلول وتقدير التكلفة خلال 24 ساعة.",
  fNamaPh: "اسمك", fButuhPh: "— أحتاج… —",
  opt1: "موقع / حلول تقنية", opt2: "برمجية / تطبيق", opt3: "إعلان / تسويق رقمي", opt4: "تصميم / هوية", opt5: "أخرى / استشارة أولاً",
  submit: "أرسل عبر واتساب",
  ctaAlt: "أو راسلنا مباشرة: <a href=\"https://wa.me/62895637319465\" target=\"_blank\" rel=\"noopener\'><strong>+62 895-6373-19465</strong></a>",
  ftDesc: "خدمات إبداعية ورقمية: حلول تقنية وتطوير برمجيات وإعلان وتصميم. شريك واحد لعلامات جاهزة للارتقاء.",
  ftSvc: "الخدمات", ftNav: "روابط", ftHub: "تواصل معنا",
  ftHours: "الاثنين–السبت · 09:00–18:00 بتوقيت غرب إندونيسيا",
  ftBase: "© <span id=\"year\'></span> كرياتيفا نتورك. جميع الحقوق محفوظة. <span class=\"syarat\'>*تطبق شروط وأحكام الضمان.</span>",
  waAria: "تحدث واتساب", topAria: "عودة للأعلى", toastInit: "جارٍ فتح واتساب…",
  promo: "مرحباً كرياتيفا نتورك! مهتم بعرض خصم 20%.",
  nav: "مرحباً كرياتيفا نتورك! أريد استشارة مجانية.",
  hero: "مرحباً كرياتيفا نتورك! أريد استشارة مجانية عن احتياجات عملي الرقمية.",
  it: "مرحباً كرياتيفا نتورك! أحتاج خدمات الحلول التقنية.",
  sw: "مرحباً كرياتيفا نتورك! أحتاج تطوير برمجية/تطبيق.",
  ads: "مرحباً كرياتيفا نتورك! أحتاج خدمات الإعلان والتسويق الرقمي.",
  des: "مرحباً كرياتيفا نتورك! أحتاج خدمات التصميم والهوية.",
  porto: "مرحباً كرياتيفا نتورك! أريد رؤية ملف الأعمال الكامل.",
  starter: "مرحباً كرياتيفا نتورك! مهتم بباقة الانطلاقة.",
  bisnis: "مرحباً كرياتيفا نتورك! مهتم بباقة الأعمال.",
  enter: "مرحباً كرياتيفا نتورك! أريد عرض سعر لباقة المؤسسات.",
  float: "مرحباً كرياتيفا نتورك! أريد استشارة."
},
ru: {
  docTitle: "Kreativa Network — креатив и digital (IT, софт, реклама, дизайн)",
  metaDesc: "Kreativa Network — ваш креативный и digital-партнёр: IT-решения, разработка ПО, реклама и дизайн. Бесплатная консультация в WhatsApp.",
  waFormTpl: "Здравствуйте, Kreativa Network! Я {nama}. Мне нужно: {butuh}. Пришлите, пожалуйста, информацию и предложение. Спасибо.",
  toastThanks: "Спасибо, {nama}! Открываем WhatsApp…",
  rotWords: ["машину продаж", "премиум-бренд", "растущий доход", "рост бизнеса"],
  preText: "Готовим ваш цифровой опыт…",
  topText: "Акция месяца: <strong>скидка 20%</strong> на сайт-визитку + фирменный стиль",
  topClaim: "Забрать скидку →",
  nHome: "Главная", nSvc: "Услуги", nWhy: "Преимущества", nPorto: "Портфолио", nHarga: "Цены", nFaq: "FAQ", nKontak: "Контакты",
  navCta: "Бесплатная консультация", hamAria: "Открыть меню",
  badge: "Креативный и digital-партнёр №1 для МСП и корпораций",
  h1a: "Создайте бренд", h1dream: "своей мечты", h1b: "и превратите его в",
  lead: "Kreativa Network помогает бизнесу <span class=\"hl\" style=\"--d:1s\'>выйти на новый уровень</span> через <strong>IT-решения, софт, рекламу и дизайн</strong> — <span class=\"hl\" style=\"--d:1.15s\'>одно окно</span>, <span class=\"hl\" style=\"--d:1.3s\'>измеримый результат</span>, <span class=\"hl\" style=\"--d:1.45s\'>гарантия правок</span>.",
  heroWa: "Написать в WhatsApp", heroSvc: "Смотреть услуги ↓",
  trust: "<strong>120+ довольных клиентов</strong> · рейтинг 4.9/5 по проверенным отзывам",
  mockStatL: "Выручка клиентов", mockStatT: "▲ за 6 месяцев",
  mWeb: "Корпоративный сайт", mAds: "Реклама Meta Ads", mLogo: "Ребрендинг логотипа", mDone: "Готово",
  f1: "Безлимит правок*", f2: "Запуск &lt; 14 дней",
  lblProj: "Проектов сдано", lblCli: "Активных клиентов", lblExp: "Опыта", lblHappy: "Довольных клиентов", sfxYr: "лет",
  svcKick: "КЛЮЧЕВЫЕ УСЛУГИ",
  svcH2: "Один партнёр для всех ваших <span class=\"grad\'>digital-задач</span>",
  svcSub: "Нажмите на услугу для деталей и сразу проконсультируйтесь в WhatsApp.",
  tabIt: "IT-решения", tabSw: "Софт", tabAds: "Реклама", tabDes: "Дизайн",
  itH: "IT-решения и инфраструктура",
  itP: "Безопасный, быстрый и масштабируемый технологический фундамент для вашего бизнеса.",
  itLi1: "Корпоративные сайты, интернет-магазины и лендинги",
  itLi2: "Обслуживание, безопасность и регулярные бэкапы",
  itLi3: "Интеграции: платёжные шлюзы, CRM, ERP, API",
  itLi4: "IT-консалтинг и аудит для снижения затрат",
  itPrice: "от <strong>Rp 1,5 jt</strong>", itBtn: "Выбрать услугу →",
  itArt: "Быстрые, безопасные и SEO-дружелюбные сайты",
  swH: "Разработка ПО",
  swP: "Индивидуальные приложения, сокращающие рутину и ускоряющие рост.",
  swLi1: "Мобильные приложения Android и iOS (Flutter / React Native)",
  swLi2: "Инфосистемы: POS, склад, HRIS, учебные, клиники",
  swLi3: "Дашборды и автоматизация отчётов в реальном времени",
  swLi4: "Исходный код — ваш + полная документация",
  swPrice: "от <strong>Rp 8 jt</strong>", swBtn: "Выбрать услугу →",
  swArt: "Приложения под процессы вашего бизнеса",
  adH: "Реклама и digital-маркетинг",
  adP: "Реклама с прозрачными данными — каждый рупий под учётом.",
  adLi1: "Meta Ads, Google Ads, TikTok Ads — запуск + оптимизация",
  adLi2: "SEO и контент-маркетинг для органики",
  adLi3: "Ведение соцсетей + продающие тексты",
  adLi4: "Понятные еженедельные отчёты",
  adPrice: "от <strong>Rp 2,5 jt/мес</strong>", adBtn: "Выбрать услугу →",
  adArt: "Средний ROAS клиентов 4–6x",
  deH: "Дизайн и брендинг",
  deP: "Премиальная визуализация: бренд выглядит дорого и вызывает доверие.",
  deLi1: "Логотип и айдентика (полный гайдлайн)",
  deLi2: "UI/UX-дизайн сайтов и приложений",
  deLi3: "Дизайн постов, баннеров, упаковки и презентаций",
  deLi4: "Гарантия правок до результата*",
  dePrice: "от <strong>Rp 750 rb</strong>", deBtn: "Выбрать услугу →",
  deArt: "Гайдлайны для печати и digital",
  advKick: "ПОЧЕМУ МЫ",
  advH2: "Почему 120+ компаний доверяют <span class=\"grad\'>Kreativa Network</span>",
  c1h: "30+ лет суммарного опыта",
  c1p: "Senior-команда разных профилей — проверенные маркетинговые стратегии, без гаданий.",
  c2h: "Быстро и в срок",
  c2p: "Чёткие сроки в договоре. Сайты за &lt; 14 дней, ответ на правки &lt; 24 часов.",
  c3h: "Прозрачные цены",
  c3p: "Смета заранее, без скрытых платежей. Гибко под бюджет МСП.",
  c4h: "Гарантия и поддержка",
  c4p: "Гарантия правок, 30 дней гарантии на баги и сопровождение после запуска.",
  c5h: "Опора на данные",
  c5p: "Каждое решение — на основе исследований и аналитики: измеримый результат, а не просто красиво.",
  c6h: "Одно окно — всё решено",
  c6p: "IT, софт, реклама и дизайн в одной команде — меньше координации и затрат.",
  poKick: "ПОРТФОЛИО",
  poH2: "Работы, которые говорят <span class=\"grad\'>цифрами</span>",
  chipAll: "Все", chipWeb: "Сайты и приложения", chipBrand: "Брендинг", chipAds: "Реклама",
  w1h: "Модный интернет-магазин", w1p: "E-commerce + платёжный шлюз · <strong>выручка +187%</strong>",
  w2h: "Ребрендинг кофейни Nusantara", w2p: "Логотип + упаковка · <strong>повторные покупки +64%</strong>",
  w3h: "Meta Ads для клиники красоты", w3p: "Лидогенерация · <strong>ROAS 5.2x</strong>",
  w4h: "Учебная система школы", w4p: "Веб-приложение + онлайн-приём · <strong>экономия 20 ч/нед</strong>",
  w5h: "Презентация застройщика", w5p: "Профиль + премиум-брошюра · <strong>сделки +41%</strong>",
  w6h: "TikTok Ads для кафе", w6p: "Контент + реклама · <strong>3,2 млн просмотров / 30 дней</strong>",
  poMore: "Запросить полное портфолио →",
  stKick: "КАК МЫ РАБОТАЕМ",
  stH2: "От первого сообщения до <span class=\"grad\'>запуска</span> — так просто",
  s1h: "Бесплатная консультация", s1p: "Напишите в WhatsApp, расскажите о задачах и целях бизнеса.",
  s2h: "Предложение и дизайн", s2p: "Прозрачная смета + начальная концепция за 2–3 дня.",
  s3h: "Реализация и правки", s3p: "Прогресс в реальном времени, правим до вашего согласия.",
  s4h: "Запуск и сопровождение", s4p: "Официальный релиз + обучение + 30 дней сопровождения.",
  teKick: "ОТЗЫВЫ",
  teH2: "Что говорят те, кто уже <span class=\"grad\'>вырос</span>",
  q1: "“Сайт от Kreativa сделал мой бизнес профессиональным. Онлайн-заказы удвоились за 3 месяца!”<footer>— <strong>Анди Р.</strong>, владелец fashion-магазина</footer>",
  q2: "“Аккуратная реклама и понятные отчёты. ROAS стабильно выше 4x. Очень рекомендую.”<footer>— <strong>Белла Т.</strong>, маркетолог клиники</footer>",
  q3: "“Учебная система резко сократила работу администраторов. Поддержка отвечает быстро.”<footer>— <strong>Х. Махмуд</strong>, директор школы</footer>",
  prKick: "ИНВЕСТИЦИИ",
  prH2: "Честные цены, <span class=\"grad\'>максимум результата</span>",
  prSub: "Все пакеты настраиваются. Нажмите, чтобы обсудить задачу.",
  p1n: "Старт", p1s: "Для начинающего МСП", uJt: " jt",
  p1li1: "Лендинг на 1 экран", p1li2: "Базовые тексты", p1li3: "Интеграция WhatsApp", p1li4: "2 правки · запуск за 7 дней",
  p1b: "Выбрать Старт",
  hot: "ХИТ ПРОДАЖ", p2n: "Бизнес", p2s: "Для растущего бизнеса", uJt2: " jt",
  p2li1: "Сайт-визитка 5–8 страниц", p2li2: "Логотип + мини-гайд", p2li3: "Базовое SEO + аналитика", p2li4: "5 правок · запуск за 14 дней",
  p2b: "Выбрать Бизнес",
  p3n: "Enterprise", p3s: "Софт и кампании масштаба", p3c: "Индивидуально",
  p3li1: "Приложения / инфосистемы", p3li2: "Ведение рекламы + креатив", p3li3: "Личный менеджер проекта", p3li4: "SLA и приоритетная гарантия",
  p3b: "Запросить предложение",
  fqKick: "FAQ",
  fqH2: "Частые <span class=\"grad\'>вопросы</span>",
  f1q: "Сколько делается сайт?",
  f1a: "Лендинг — ±7 дней, сайт-визитка — ±14 дней, приложения — 1–3 месяца в зависимости от сложности. Сроки чётко фиксируем в договоре.",
  f2q: "Есть ли гарантия правок?",
  f2a: "Да. Каждый пакет включает лимит правок, а для дизайна действует гарантия до результата в разумных согласованных рамках.",
  f3q: "Как проходит оплата?",
  f3a: "Предоплата 50% для старта, остальное после сдачи. Для крупных проектов — поэтапно. Всё — со счётом и официальным договором.",
  f4q: "Исходный код будет моим?",
  f4a: "Да, для индивидуальных сайтов и приложений полный исходный код + документация передаются после оплаты.",
  f5q: "Работаете с клиентами из других городов?",
  f5a: "Конечно. 70% наших клиентов — из других городов: всё онлайн (WhatsApp, Zoom, дашборд прогресса) с тем же качеством.",
  ctaH2: "Готовы, чтобы бизнес выглядел <span class=\"grad\'>дорого и надёжно?</span>",
  ctaP: "<strong>100% бесплатная консультация без обязательств</strong>. Расскажите о задаче — ответим решением и оценкой за 24 часа.",
  fNamaPh: "Ваше имя", fButuhPh: "— Мне нужно… —",
  opt1: "Сайт / IT-решения", opt2: "Софт / приложение", opt3: "Реклама / digital-маркетинг", opt4: "Дизайн / брендинг", opt5: "Другое / сначала консультация",
  submit: "Отправить в WhatsApp",
  ctaAlt: "Или напишите напрямую: <a href=\"https://wa.me/62895637319465\" target=\"_blank\" rel=\"noopener\'><strong>+62 895-6373-19465</strong></a>",
  ftDesc: "Креатив и digital: IT-решения, разработка ПО, реклама и дизайн. Один партнёр для брендов, готовых расти.",
  ftSvc: "Услуги", ftNav: "Навигация", ftHub: "Свяжитесь с нами",
  ftHours: "Пн–Сб · 09:00–18:00 WIB",
  ftBase: "© <span id=\"year\'></span> Kreativa Network. Все права защищены. <span class=\"syarat\'>*Действуют условия гарантии.</span>",
  waAria: "Написать в WhatsApp", topAria: "Наверх", toastInit: "Открываем WhatsApp…",
  promo: "Здравствуйте, Kreativa Network! Интересует акция −20%.",
  nav: "Здравствуйте, Kreativa Network! Хочу бесплатную консультацию.",
  hero: "Здравствуйте, Kreativa Network! Хочу бесплатную консультацию по digital-задачам бизнеса.",
  it: "Здравствуйте, Kreativa Network! Нужны IT-услуги.",
  sw: "Здравствуйте, Kreativa Network! Нужна разработка софта/приложения.",
  ads: "Здравствуйте, Kreativa Network! Нужны реклама и digital-маркетинг.",
  des: "Здравствуйте, Kreativa Network! Нужны дизайн и брендинг.",
  porto: "Здравствуйте, Kreativa Network! Хочу посмотреть полное портфолио.",
  starter: "Здравствуйте, Kreativa Network! Интересует пакет Старт.",
  bisnis: "Здравствуйте, Kreativa Network! Интересует пакет Бизнес.",
  enter: "Здравствуйте, Kreativa Network! Хочу предложение по пакету Enterprise.",
  float: "Здравствуйте, Kreativa Network! Хочу консультацию."
}
};

// ---------- logic ----------
var KN_CUR = "id";
try { KN_CUR = localStorage.getItem("kn-lang") || "id"; } catch (e) {}
if (KN_LANGS.indexOf(KN_CUR) < 0) KN_CUR = "id";

// Snapshot default Indonesia dari DOM (sekali saat load)
(function snapshot() {
  if (!I18N.id) I18N.id = {};
  function save(map, attr, get) {
    document.querySelectorAll("[" + attr + "]").forEach(function (el) {
      var k = el.getAttribute(attr);
      if (!(k in map)) map[k] = get(el);
    });
  }
  save(I18N.id, "data-i18n", function (el) { return el.innerHTML; });
  save(I18N.id, "data-i18n-ph", function (el) { return el.getAttribute("placeholder") || ""; });
  save(I18N.id, "data-i18n-aria", function (el) { return el.getAttribute("aria-label") || ""; });
  save(I18N.id, "data-wa-key", function (el) { return el.getAttribute("data-wa") || ""; });
})();

function KN_T(key, vars) {
  var d = (I18N[KN_CUR] && I18N[KN_CUR][key] != null) ? I18N[KN_CUR][key] : I18N.id[key];
  if (d == null) return "";
  if (vars) Object.keys(vars).forEach(function (k) { d = d.split("{" + k + "}").join(vars[k]); });
  return d;
}
window.KN_T = KN_T;

function KN_apply(l) {
  if (KN_LANGS.indexOf(l) < 0) l = "id";
  KN_CUR = l;
  try { localStorage.setItem("kn-lang", l); } catch (e) {}
  var D = I18N[l] || {}, F = I18N.id;
  function pick(k) { return (D[k] != null) ? D[k] : F[k]; }
  document.querySelectorAll("[data-i18n]").forEach(function (el) {
    var v = pick(el.getAttribute("data-i18n"));
    if (v != null) el.innerHTML = v;
  });
  document.querySelectorAll("[data-i18n-ph]").forEach(function (el) {
    var v = pick(el.getAttribute("data-i18n-ph"));
    if (v != null) el.setAttribute("placeholder", v);
  });
  document.querySelectorAll("[data-i18n-aria]").forEach(function (el) {
    var v = pick(el.getAttribute("data-i18n-aria"));
    if (v != null) el.setAttribute("aria-label", v);
  });
  document.querySelectorAll("[data-wa-key]").forEach(function (el) {
    var v = pick(el.getAttribute("data-wa-key"));
    if (v) el.href = "https://wa.me/" + KN_WA_NUM + "?text=" + encodeURIComponent(v);
  });
  var t = pick("docTitle");
  if (t) document.title = t;
  var md = document.querySelector('meta[name="description"]');
  var mdd = pick("metaDesc");
  if (md && mdd) md.setAttribute("content", mdd);
  var rw = pick("rotWords");
  if (rw && rw.length) {
    window.KN_ROT = rw;
    var r = document.getElementById("rotWord");
    if (r) r.textContent = rw[0];
    if (window.KN_ROTres) window.KN_ROTres();
  }
  document.documentElement.lang = l;
  document.documentElement.dir = (l === "ar") ? "rtl" : "ltr";
  document.querySelectorAll(".lang-btn").forEach(function (b) {
    b.classList.toggle("active", b.getAttribute("data-lang") === l);
  });
  var y = document.getElementById("year");
  if (y) y.textContent = new Date().getFullYear();
}

document.querySelectorAll(".lang-btn").forEach(function (b) {
  b.addEventListener("click", function () { KN_apply(b.getAttribute("data-lang")); });
});
KN_apply(KN_CUR);
